spring:
  application:
    name: api.gateway

  security:
    oauth2:
      client:
        registration:
          oauth2-client-credentials:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - roles
            authorization-grant-type: client_credentials
        provider:
          oauth2-client-credentials:
            issuer-uri: http://localhost:8080/realms/keycloak-realm
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/keycloak-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/{version}/flight/**
          filters:
            - TokenRelay


server:
  port: 8081