spring:
  jpa:
    datasource-url: jdbc:postgresql://localhost:5432/spring_demo
    datasource-username: postgres
    datasource-password: postgres
    datasource-driver-class-name: org.postgresql.Driver
    hibernate-ddl-auto: update
    packagesToScan: sample.spring.student
    hibernate-column_ordering_strategy: legacy

#  flyway:
#    enabled: false
#    baseline-on-migrate: true
#    supported-database-check-disabled: true
#    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchangeName: student
    exchangeType: topic