spring:
  profiles:
    active: dev
  application:
    name: student

logging:
  name: student-logger
  level:
    root: INFO

jpa:
  datasource-url: jdbc:postgresql://localhost:5432/spring_demo
  datasource-username: postgres
  datasource-password: postgres
  datasource-driver-class-name: org.postgresql.Driver
  hibernate-ddl-auto: validate
  packagesToScan: sample.spring.student
  hibernate-column_ordering_strategy: legacy
  hibernate-show_sql: false
  hibernate-format_sql: false

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  baseline-version: 0
  validate-on-migrate: true
  clean-disabled: false

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchangeName: student
  exchangeType: topic

otel:
  collector:
    enabled: false
    service-name: student
    service-version: 1.0.0
    endpoint: http://localhost:4317
